### ISSUE TITLE
Missing Decrypted Certificates

### ISSUE THREAD

**Issue by devlman127** [mikage-emu/saveShop#16]
After running the commands to decrypt the 3DS certificate files, no decrypted files are created. It simply says
`enc: Use -help for summary.` Is the given commands to decrypt the files correct?

**Comment by Divi-0** [comment]
yes, I don't know what the issue in your case is, but I executed it on ubuntu

**Comment by neobrain** [comment]
Yeah, the commands will work if executed right. Maybe something about the AES key? `<aeskey_0x0d>` must be replaced with the actual AES key without leading `0x` (and the `<` and `>` should be removed).

**Comment by devlman127** [comment]
I already made sure my AES key didn't have the leading 0x and the <> were removed. 
I copied the command (except the AES key) straight from the readme.md
Shouldn't that be fixed so the readme is corrrect?

**Comment by neobrain** [comment]
>  Shouldn't that be fixed so the readme is corrrect?

I don't know what's wrong in your case, but the Readme instructions are working for several people. There's nothing I can do to help.

For what it's worth, if you can't get the certificate decrypted, you can use the `--omit-ninja-contents` flag instead to skip some metadata.

**Comment by devlman127** [comment]
What metadata does the ninja server contain?

**Comment by mariomadproductions** [comment]
Prices, for instance. But it seems like they've removed the prices from the ninja xmls now...
