### ISSUE TITLE
wiiu eshop scrapper not working

### ISSUE THREAD

**Issue by pokemontest1234** [mikage-emu/saveShop#3]
when executing the command below in powershell I get this error message.
."\saveShop.exe --regions DE fetch-all --cert .\ctr-common-1.pem"
ctr-common-1.pem is dumped from my 3ds.(do i need to get it from my wiiu and if yes how)
all i changed was the shop id from 1 to 2
Error message:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:540:56

**Comment by neobrain** [comment]
Thanks for testing! See https://github.com/mikage-emu/saveShop/issues/2#issuecomment-1455083939 for patches fixing Wii U eShop support.

**Comment by pokemontest1234** [comment]
sorry for this beginner question but i have tried to apply the patch but i can't seam to get it to apply can you tell me how i can apply it?
