### ISSUE TITLE
Is there a guide for obtaining the value for slot0x0DKeyN?

### ISSUE THREAD

**Issue by Lanklow** [mikage-emu/saveShop#8]
The Citra wiki page on the topic has no advice about how to dump the keys themselves; just how to format 'aes_keys.txt' file.

I tried keys obtained through *other methods*, and I got a 'bad decrypt' error.

How did _you_ get the appropriate keys?

**Comment by neobrain** [comment]
openssl for unknown reasons throws a `bad decrypt` error even with the correct keys. Try running the `curl` verification steps outlined in the Readme to check if the file is fine. (For extra certainty, the md5sum of the resulting file should be 47a75886a0672b7f3d13603218b7b4bb).

**Comment by neobrain** [comment]
For reference, the key itself is present in plaintext in the 3DS ARM9 bootrom, but I don't know its offset from the top off my head. (The Citra source suggests it's shortly after byte offset 55760.)

**Comment by Lanklow** [comment]
My checksum matches. Thank you for the help.
