### ISSUE TITLE
web app doesn't display categories for wiiu and shop id 3 and 4

### ISSUE THREAD

**Issue by pokemontest1234** [mikage-emu/saveShop#9]
web app doesn't display categories for scrapped wiiu eshop data

**Comment by pokemontest1234** [comment]
also seams to happen with the shop id 3 and 4

**Comment by neobrain** [comment]
Yeah, the webapp hasn't been tested on non-3ds platforms. PRs are welcome, as this is something I don't plan to work on personally :)
